In [2]:
import pandas as pd
import geopandas as gpd

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)
pd.set_option('display.max_rows', 100)

In [4]:
dane_epsg2180_lublin = gpd.read_file("data/dane_epsg2180_lublin.gml", encoding="UTF-8")

In [5]:
dane_epsg2180_lublin.head()

           gml_id serwis_rcn teryt tran_przestrzen_nazw                   tran_lokalny_id_iip       tran_wersja_id       tran_rodzaj_trans tran_rodzaj_rynku tran_sprzedajacy  tran_kupujacy tran_cena_brutto  tran_vat                dok_data           nier_rodzaj                          nier_prawo nier_udzial nier_pow_gruntu nier_cena_brutto  nier_vat                          lok_id_lokalu lok_nr_lokalu lok_funkcja lok_liczba_izb lok_nr_kond lok_pow_uzyt lok_pow_przyn lok_cena_brutto   lok_vat                                 lok_adres    dzielnica                       geometry
0  lokale.7652240       None  0609    PL.PZGiK.9349.RCN  5A4905BC-D6A2-40D6-8353-6E94AF99B6AD                  NaN              wolnyRynek               NaN      osobaPrawna  osobaFizyczna           370000       NaN  2026-01-26 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1            0.14           370000       NaN            060911_2.0007.494_BUD.1_LOK         1_LOK  mieszkalna            NaN         NaN         35.8           NaN             NaN       NaN                                       NaN          NaN  POINT (749233.476 386125.694)
1  lokale.7702785       None  0663    PL.PZGiK.4884.RCN  98781cfc-2bb7-4d85-9664-c969a4b2692f  2013-02-21T14:26:22  sprzedazBezprzetargowa         pierwotny      osobaPrawna  osobaFizyczna            20000       NaN  2012-09-27 02:00:00+02  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN            20000       NaN  066301_1.0027.AR_12.34/1.1_BUD.33_LOK        33_LOK       garaz              1           0          396           NaN           20000       NaN      MSC:Lublin;UL:Kryształowa;NR_PORZ:30   Węglin Pd.  POINT (744316.367 378735.781)
2  lokale.7691559       None  0663    PL.PZGiK.4884.RCN  dd4ba0a2-1bf5-4246-913b-643e6abbecad  2013-01-11T11:11:48              wolnyRynek            wtorny    osobaFizyczna  osobaFizyczna           160000       NaN  2012-09-24 02:00:00+02  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN           160000       NaN     066301_1.0019.AR_9.9/8.1_BUD.1_LOK         1_LOK  mieszkalna              3           4        45.84           NaN          160000       NaN          MSC:Lublin;UL:Puchacza;NR_PORZ:8    Bronowice   POINT (750569.449 380204.84)
3  lokale.7682760       None  0663    PL.PZGiK.4884.RCN  33e4defe-db48-4760-8efd-ce127c4b8d75  2013-03-14T09:57:40              wolnyRynek            wtorny    osobaFizyczna  osobaFizyczna           257000       NaN  2012-12-07 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN           257000       NaN    066301_1.0006.AR_5.1/4.13_BUD.1_LOK         1_LOK  mieszkalna              4           1         69.6           4.4          257000       NaN     MSC:Lublin;UL:Leszetyckiego;NR_PORZ:6  Czechów Pł.  POINT (747737.827 384676.722)
4  lokale.7693503       None  0663    PL.PZGiK.4884.RCN  d2afa76b-927a-4325-9f0f-74c3c9fbc15a  2013-07-05T14:01:57  sprzedazBezprzetargowa         pierwotny      osobaPrawna  osobaFizyczna           225000  16666.67  2013-04-22 02:00:00+02  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN           225000  16666.67   066301_1.0024.AR_7.12/2.1_BUD.86_LOK        86_LOK  mieszkalna              3           4        49.62         10.79          225000  16666.67  MSC:Lublin;UL:Strzeszewskiego;NR_PORZ:17    Ponikwoda  POINT (749805.079 384621.036)

In [6]:
def rozdziel_adres(df, kolumna_zrodlowa='lok_adres'):
    df_copy = df.copy()

    df_copy['Miejscowość'] = None
    df_copy['Ulica'] = None
    df_copy['Numer'] = None
    

    for idx, row in df_copy.iterrows():
        if pd.notna(row[kolumna_zrodlowa]):
            adres_str = str(row[kolumna_zrodlowa])

            pary = adres_str.split(';')
            
            for para in pary:
                if ':' in para:
                    klucz, wartość = para.split(':', 1)
                    klucz = klucz.strip()
                    wartość = wartość.strip()
                    
                    if klucz == 'MSC':
                        df_copy.at[idx, 'Miejscowość'] = wartość
                    elif klucz == 'UL':
                        df_copy.at[idx, 'Ulica'] = wartość
                    elif klucz == 'NR_PORZ':
                        df_copy.at[idx, 'Numer'] = wartość
    
    
    df_copy = df_copy.drop(columns=[kolumna_zrodlowa])

    return df_copy

In [7]:
dane_epsg2180_lublin = rozdziel_adres(dane_epsg2180_lublin, "lok_adres")

In [8]:
dane_epsg2180_lublin.head()

           gml_id serwis_rcn teryt tran_przestrzen_nazw                   tran_lokalny_id_iip       tran_wersja_id       tran_rodzaj_trans tran_rodzaj_rynku tran_sprzedajacy  tran_kupujacy tran_cena_brutto  tran_vat                dok_data           nier_rodzaj                          nier_prawo nier_udzial nier_pow_gruntu nier_cena_brutto  nier_vat                          lok_id_lokalu lok_nr_lokalu lok_funkcja lok_liczba_izb lok_nr_kond lok_pow_uzyt lok_pow_przyn lok_cena_brutto   lok_vat    dzielnica                       geometry Miejscowość            Ulica Numer
0  lokale.7652240       None  0609    PL.PZGiK.9349.RCN  5A4905BC-D6A2-40D6-8353-6E94AF99B6AD                  NaN              wolnyRynek               NaN      osobaPrawna  osobaFizyczna           370000       NaN  2026-01-26 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1            0.14           370000       NaN            060911_2.0007.494_BUD.1_LOK         1_LOK  mieszkalna            NaN         NaN         35.8           NaN             NaN       NaN          NaN  POINT (749233.476 386125.694)        None             None  None
1  lokale.7702785       None  0663    PL.PZGiK.4884.RCN  98781cfc-2bb7-4d85-9664-c969a4b2692f  2013-02-21T14:26:22  sprzedazBezprzetargowa         pierwotny      osobaPrawna  osobaFizyczna            20000       NaN  2012-09-27 02:00:00+02  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN            20000       NaN  066301_1.0027.AR_12.34/1.1_BUD.33_LOK        33_LOK       garaz              1           0          396           NaN           20000       NaN   Węglin Pd.  POINT (744316.367 378735.781)      Lublin      Kryształowa    30
2  lokale.7691559       None  0663    PL.PZGiK.4884.RCN  dd4ba0a2-1bf5-4246-913b-643e6abbecad  2013-01-11T11:11:48              wolnyRynek            wtorny    osobaFizyczna  osobaFizyczna           160000       NaN  2012-09-24 02:00:00+02  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN           160000       NaN     066301_1.0019.AR_9.9/8.1_BUD.1_LOK         1_LOK  mieszkalna              3           4        45.84           NaN          160000       NaN    Bronowice   POINT (750569.449 380204.84)      Lublin         Puchacza     8
3  lokale.7682760       None  0663    PL.PZGiK.4884.RCN  33e4defe-db48-4760-8efd-ce127c4b8d75  2013-03-14T09:57:40              wolnyRynek            wtorny    osobaFizyczna  osobaFizyczna           257000       NaN  2012-12-07 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN           257000       NaN    066301_1.0006.AR_5.1/4.13_BUD.1_LOK         1_LOK  mieszkalna              4           1         69.6           4.4          257000       NaN  Czechów Pł.  POINT (747737.827 384676.722)      Lublin    Leszetyckiego     6
4  lokale.7693503       None  0663    PL.PZGiK.4884.RCN  d2afa76b-927a-4325-9f0f-74c3c9fbc15a  2013-07-05T14:01:57  sprzedazBezprzetargowa         pierwotny      osobaPrawna  osobaFizyczna           225000  16666.67  2013-04-22 02:00:00+02  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN           225000  16666.67   066301_1.0024.AR_7.12/2.1_BUD.86_LOK        86_LOK  mieszkalna              3           4        49.62         10.79          225000  16666.67    Ponikwoda  POINT (749805.079 384621.036)      Lublin  Strzeszewskiego    17

In [9]:
def add_xy_from_geometry(df: gpd.GeoDataFrame) -> pd.DataFrame:
    out = df.copy()

    cx = out.geometry.x
    cy = out.geometry.y
    out["coord_x"] = cx
    out["coord_y"] = cy

    out = out.drop(columns=['geometry'])

    return out

In [10]:
dane_epsg2180_lublin = add_xy_from_geometry(dane_epsg2180_lublin)

In [11]:
dane_epsg2180_lublin.head()

           gml_id serwis_rcn teryt tran_przestrzen_nazw                   tran_lokalny_id_iip       tran_wersja_id       tran_rodzaj_trans tran_rodzaj_rynku tran_sprzedajacy  tran_kupujacy tran_cena_brutto  tran_vat                dok_data           nier_rodzaj                          nier_prawo nier_udzial nier_pow_gruntu nier_cena_brutto  nier_vat                          lok_id_lokalu lok_nr_lokalu lok_funkcja lok_liczba_izb lok_nr_kond lok_pow_uzyt lok_pow_przyn lok_cena_brutto   lok_vat    dzielnica Miejscowość            Ulica Numer        coord_x        coord_y
0  lokale.7652240       None  0609    PL.PZGiK.9349.RCN  5A4905BC-D6A2-40D6-8353-6E94AF99B6AD                  NaN              wolnyRynek               NaN      osobaPrawna  osobaFizyczna           370000       NaN  2026-01-26 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1            0.14           370000       NaN            060911_2.0007.494_BUD.1_LOK         1_LOK  mieszkalna            NaN         NaN         35.8           NaN             NaN       NaN          NaN        None             None  None  749233.475913  386125.693958
1  lokale.7702785       None  0663    PL.PZGiK.4884.RCN  98781cfc-2bb7-4d85-9664-c969a4b2692f  2013-02-21T14:26:22  sprzedazBezprzetargowa         pierwotny      osobaPrawna  osobaFizyczna            20000       NaN  2012-09-27 02:00:00+02  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN            20000       NaN  066301_1.0027.AR_12.34/1.1_BUD.33_LOK        33_LOK       garaz              1           0          396           NaN           20000       NaN   Węglin Pd.      Lublin      Kryształowa    30  744316.366910  378735.781040
2  lokale.7691559       None  0663    PL.PZGiK.4884.RCN  dd4ba0a2-1bf5-4246-913b-643e6abbecad  2013-01-11T11:11:48              wolnyRynek            wtorny    osobaFizyczna  osobaFizyczna           160000       NaN  2012-09-24 02:00:00+02  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN           160000       NaN     066301_1.0019.AR_9.9/8.1_BUD.1_LOK         1_LOK  mieszkalna              3           4        45.84           NaN          160000       NaN    Bronowice      Lublin         Puchacza     8  750569.448862  380204.839876
3  lokale.7682760       None  0663    PL.PZGiK.4884.RCN  33e4defe-db48-4760-8efd-ce127c4b8d75  2013-03-14T09:57:40              wolnyRynek            wtorny    osobaFizyczna  osobaFizyczna           257000       NaN  2012-12-07 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN           257000       NaN    066301_1.0006.AR_5.1/4.13_BUD.1_LOK         1_LOK  mieszkalna              4           1         69.6           4.4          257000       NaN  Czechów Pł.      Lublin    Leszetyckiego     6  747737.826590  384676.722224
4  lokale.7693503       None  0663    PL.PZGiK.4884.RCN  d2afa76b-927a-4325-9f0f-74c3c9fbc15a  2013-07-05T14:01:57  sprzedazBezprzetargowa         pierwotny      osobaPrawna  osobaFizyczna           225000  16666.67  2013-04-22 02:00:00+02  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN           225000  16666.67   066301_1.0024.AR_7.12/2.1_BUD.86_LOK        86_LOK  mieszkalna              3           4        49.62         10.79          225000  16666.67    Ponikwoda      Lublin  Strzeszewskiego    17  749805.079056  384621.036029

Odrzucenie kolumn na podstawie wiedzy

In [12]:
columns_to_drop = [
    "gml_id", 
    "serwis_rcn",
    "teryt",
    "tran_przestrzen_nazw",
    "tran_lokalny_id_iip",
    "tran_wersja_id",
    "tran_vat",
    "nier_cena_brutto",
    "nier_vat",
    "lok_id_lokalu",
    "lok_cena_brutto",
    "lok_vat"
            ]

dane_epsg2180_lublin = dane_epsg2180_lublin.drop(columns=columns_to_drop)

In [13]:
dane_epsg2180_lublin.head()

        tran_rodzaj_trans tran_rodzaj_rynku tran_sprzedajacy  tran_kupujacy tran_cena_brutto                dok_data           nier_rodzaj                          nier_prawo nier_udzial nier_pow_gruntu lok_nr_lokalu lok_funkcja lok_liczba_izb lok_nr_kond lok_pow_uzyt lok_pow_przyn    dzielnica Miejscowość            Ulica Numer        coord_x        coord_y
0              wolnyRynek               NaN      osobaPrawna  osobaFizyczna           370000  2026-01-26 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1            0.14         1_LOK  mieszkalna            NaN         NaN         35.8           NaN          NaN        None             None  None  749233.475913  386125.693958
1  sprzedazBezprzetargowa         pierwotny      osobaPrawna  osobaFizyczna            20000  2012-09-27 02:00:00+02  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN        33_LOK       garaz              1           0          396           NaN   Węglin Pd.      Lublin      Kryształowa    30  744316.366910  378735.781040
2              wolnyRynek            wtorny    osobaFizyczna  osobaFizyczna           160000  2012-09-24 02:00:00+02  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN         1_LOK  mieszkalna              3           4        45.84           NaN    Bronowice      Lublin         Puchacza     8  750569.448862  380204.839876
3              wolnyRynek            wtorny    osobaFizyczna  osobaFizyczna           257000  2012-12-07 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN         1_LOK  mieszkalna              4           1         69.6           4.4  Czechów Pł.      Lublin    Leszetyckiego     6  747737.826590  384676.722224
4  sprzedazBezprzetargowa         pierwotny      osobaPrawna  osobaFizyczna           225000  2013-04-22 02:00:00+02  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             NaN        86_LOK  mieszkalna              3           4        49.62         10.79    Ponikwoda      Lublin  Strzeszewskiego    17  749805.079056  384621.036029

In [ ]:
dane_epsg2180_lublin[dane_epsg2180_lublin["nier_pow_gruntu"].isna()==0]

               gml_id serwis_rcn teryt tran_przestrzen_nazw                   tran_lokalny_id_iip       tran_wersja_id       tran_rodzaj_trans tran_rodzaj_rynku tran_sprzedajacy  tran_kupujacy tran_cena_brutto  tran_vat                dok_data           nier_rodzaj                          nier_prawo nier_udzial nier_pow_gruntu nier_cena_brutto  nier_vat                          lok_id_lokalu lok_nr_lokalu lok_funkcja lok_liczba_izb lok_nr_kond lok_pow_uzyt lok_pow_przyn lok_cena_brutto   lok_vat    dzielnica Miejscowość                Ulica  Numer        coord_x        coord_y
0      lokale.7652240       None  0609    PL.PZGiK.9349.RCN  5A4905BC-D6A2-40D6-8353-6E94AF99B6AD                  NaN              wolnyRynek               NaN      osobaPrawna  osobaFizyczna           370000       NaN  2026-01-26 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1            0.14           370000       NaN            060911_2.0007.494_BUD.1_LOK         1_LOK  mieszkalna            NaN         NaN         35.8           NaN             NaN       NaN          NaN        None                 None   None  749233.475913  386125.693958
26     lokale.7691200       None  0663    PL.PZGiK.4884.RCN  f1d9fc8f-26ef-4ee3-9b71-15ea727cfc59  2016-01-08T14:09:46              wolnyRynek            wtorny    osobaFizyczna  osobaFizyczna           180000         0  2015-11-05 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             247           180000         0     066301_1.0029.AR_3.3/3.1_BUD.3_LOK         3_LOK  mieszkalna              2           5        42.58           NaN          180000         0  Śródmieście      Lublin              Głęboka     21  747506.247392  380888.149774
27     lokale.7682837       None  0663    PL.PZGiK.4884.RCN  87bcc695-f9c3-47f7-bbe1-800f1115893a  2016-02-26T09:27:31              wolnyRynek            wtorny    osobaFizyczna  osobaFizyczna            16000         0  2015-12-31 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym        1/53           15137            16000         0  066301_1.0032.AR_2.164/18.1_BUD.1_LOK         1_LOK       garaz              0           0       1476.3         13.32           16000         0       Sławin      Lublin            Relaksowa     14  745572.783195  383940.552355
28     lokale.7673185       None  0663    PL.PZGiK.4884.RCN  70bf5253-73ce-4fd1-8f15-226e0e50bbd9  2016-03-03T14:12:04  sprzedazBezprzetargowa         pierwotny      osobaPrawna  osobaFizyczna           300000     25045  2015-12-23 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1            3734           275000     20370   066301_1.0042.AR_4.8/16.1_BUD.12_LOK        12_LOK  mieszkalna              2           3         53.1           NaN          275000  20370.37    Ponikwoda      Lublin       Ignacego Czumy      1  749528.400564  384786.213773
29     lokale.7694925       None  0663    PL.PZGiK.4884.RCN  9d16ea4b-aa38-4dbd-b859-cf87f31178af  2016-03-31T14:00:08  sprzedazBezprzetargowa         pierwotny    osobaFizyczna  osobaFizyczna           287799     21318  2016-01-18 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1            9947           287799     21318  066301_1.0010.AR_6.1/113.3_BUD.11_LOK        11_LOK  mieszkalna              4           2        66.93          1.72          287799  21318.44    Dziesiąta      Lublin           Nowy Świat    40h  748434.895520  378998.371568
...               ...        ...   ...                  ...                                   ...                  ...                     ...               ...              ...            ...              ...       ...                     ...                   ...                                 ...         ...             ...              ...       ...                                    ...           ...         ...            ...         ...          ...           ...             ...       ...          ...         ...                  ...    ...            ...            ...
96657  lokale.7767661       None  0663    PL.PZGiK.4884.RCN  6820e1d0-4c89-4789-8f0f-394c47da1367  2025-06-23T09:08:35  sprzedazBezprzetargowa         pierwotny      osobaPrawna  osobaFizyczna           760000   56296.3  2025-04-29 02:00:00+02  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1           32626           760000   56296.3   066301_1.0008.AR_1.74/53.1_BUD.2_LOK         2_LOK  mieszkalna              4           2        68.29           NaN             NaN       NaN       Sławin      Lublin         Sławinkowska  134ea  743958.465856  385105.727721
96658  lokale.7736515       None  0663    PL.PZGiK.4884.RCN  56980382-5fff-48c6-9aee-c8c116059776  2021-03-01T12:27:02              wolnyRynek            wtorny    osobaFizyczna  osobaFizyczna            26000         0  2021-02-10 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1             205            26000         0     066301_1.0029.AR_3.1/3.1_BUD.3_LOK         3_LOK       garaz              1           0         15.6           NaN             NaN       NaN  Śródmieście      Lublin              Głęboka     29  747357.943002  380966.513410
96659  lokale.7734711       None  0663    PL.PZGiK.4884.RCN  168c3643-d407-4447-ad2f-fab398831a0b  2021-03-05T13:49:17  sprzedazBezprzetargowa         pierwotny      osobaPrawna  osobaFizyczna           447725  36552.35  2020-11-13 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1            5040           417725  30942.59  066301_1.0026.AR_6.3/60.1_BUD.115_LOK       115_LOK  mieszkalna              3           6        53.59           NaN             NaN       NaN     Wieniawa      Lublin    aleje Racławickie    28a  746588.645630  381822.000984
96660  lokale.7736926       None  0663    PL.PZGiK.4884.RCN  892d2928-64da-479b-8ae7-eccdda5bfadb  2021-04-07T10:50:21              wolnyRynek            wtorny    osobaFizyczna  osobaFizyczna           520000         0  2021-03-15 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1            2108           520000         0    066301_1.0023.AR_1.7/2.3_BUD.48_LOK        48_LOK  mieszkalna              5           2        95.71          4.28             NaN       NaN    Ponikwoda      Lublin            Cyprysowa     16  749699.787921  384298.405509
96661  lokale.7735596       None  0663    PL.PZGiK.4884.RCN  afbd6d24-4172-4550-a143-db976268a2ec  2021-04-13T11:34:23  sprzedazBezprzetargowa         pierwotny      osobaPrawna  osobaFizyczna        354818.73  31928.76  2020-12-29 01:00:00+01  nieruchomoscLokalowa  wlasnoscLokaluWrazZPrawemZwiazanym         1/1           13373        304818.73  22579.17    066301_1.0043.AR_28.63.2_BUD.20_LOK        20_LOK  mieszkalna              2           5        48.96          3.11             NaN       NaN      Wrotków      Lublin  Henryka Wolińskiego     33  747883.350315  376564.736714

[64663 rows x 34 columns]

In [ ]:
dane_epsg2180_lublin

Czyszczenie kolumn

In [ ]:
dane_epsg2180_lublin["nier_udzial"].unique()

<StringArray>
[        '1/1',        '1/53',        '4/60', '1150/104893',       '1/197',        '1/40',  '1642/50834',        '1/45',       '4/254',  '2134/28577',
 ...
 '2584/129431', '3033/287574',  '2808/75909', '1665/212159',    '201/6463', '2709/124666',      '20/100',  '1398/95468',  '2490/58181', '6645/212159']
Length: 2573, dtype: str

In [ ]:
dane_epsg2180_lublin2 = dane_epsg2180_lublin.select(("teryt"))
dane_epsg2180_lublin2

AttributeError: 'DataFrame' object has no attribute 'select'

In [ ]:
dane_epsg2180_lublin.to_parquet("dane.parquet")